# .github/workflows/actions-integration-tests.yml
name: Actions Integration Tests

on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - dev
            - main
        paths:
            - 'actions-indexer/**'
            - 'actions-indexer-pipeline/**'
            - 'actions-indexer-shared/**'
            - 'actions-indexer-repository/**'
            - '.github/workflows/actions-integration-tests.yml'
    push:
        branches:
            - dev
            - main
        paths:
            - 'actions-indexer-repository/**'

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/actions_test

jobs:
  actions-integration-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: actions_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo/target
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features postgres

      - name: Run migrations
        working-directory: actions-indexer-repository
        run: sqlx migrate run --source src/postgres/migrations

      - name: Generate sqlx query cache
        working-directory: actions-indexer-repository
        run: cargo sqlx prepare

      - name: Run integration tests
        env:
          RUST_BACKTRACE: 1
        run: |
          cargo test --test '*' --locked \
            -p actions-indexer \
            -p actions-indexer-pipeline \
            -p actions-indexer-repository \
            -p actions-indexer-shared