# .github/workflows/actions-unit-tests.yml
name: Actions Unit Tests

on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - dev
            - main
        paths:
            - 'actions-indexer/**'
            - 'actions-indexer-pipeline/**'
            - 'actions-indexer-shared/**'
            - 'actions-indexer-repository/**'
            - '.github/workflows/actions-unit-tests.yml'

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  actions-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo/target
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Cargo test unit (actions)
        env:
          RUST_BACKTRACE: 1
        run: |
          cargo test --locked --lib \
            -p actions-indexer \
            -p actions-indexer-pipeline \
            -p actions-indexer-shared \
            -p actions-indexer-repository
