name: API Unit Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'api/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'api/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Run unit tests
        run: bun run test
        env:
          DATABASE_URL: "postgresql://test:test@localhost:5432/test"
          IPFS_KEY: "test-key"
          IPFS_GATEWAY_WRITE: "https://ipfs.io"
          RPC_ENDPOINT: "https://rpc.testnet.example.com"
          CHAIN_ID: "80451"
          DEPLOYER_PK: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"