name: Indexer Check

on:
  push:
    branches: [main]
    paths: [indexer/**, stream/**, wire/**, indexer_utils/**]
  pull_request:
    branches: [main]
    paths: [indexer/**, stream/**, wire/**, indexer_utils/**]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./indexer

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust ${{ matrix.rust }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./indexer

      - name: Build
        run: cargo build --verbose --workspace
